# Generated by Django 6.0.3 on 2026-04-28 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestor",
            name="activo",
        ),
        migrations.AddField(
            model_name="gestor",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.TextField(blank=True, default="Sin direccion"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, default="000000000", max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("estado", models.CharField(default="pendiente", max_length=50)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="miapp.cliente"
                    ),
                ),
            ],
        ),
    ]
