# Generated by Django 6.0.5 on 2026-05-24 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_remove_gestor_activo_gestor_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='autor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='imagen',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pedido',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='miapp.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
